<?php

declare(strict_types=1);

namespace Academe\Opayo\Pi\Response;

/**
 * Response to a Payment (and probably Authorise) requent when a
 * 3D Secure redirect is needed.
 *
 * @deprecated 3D Secure v1 will end March 2022; use 3DS v2 with the Secure3Dv2Redirect
 */

use Academe\Opayo\Pi\Helper;

class Secure3DRedirect extends AbstractTransaction
{
    /**
     * The acsUrl and paReq should not be stored in the database.
     */
    protected ?string $acsUrl = null;
    protected ?string $paReq = null;

    protected function setData(mixed $data): mixed
    {
        $this->setStatuses($data);

        $this->transactionId = Helper::dataGet($data, 'transactionId', null);

        $this->acsUrl = Helper::dataGet($data, 'acsUrl', null);
        $this->paReq = Helper::dataGet($data, 'paReq', null);

        return $this;
    }

    /**
     * The 3DSecure ACS URL, to send users to
     */
    public function getAcsUrl(): ?string
    {
        return $this->acsUrl;
    }

    /**
     * The 3DSecure PA REQ, the token to send along to the ACS URL
     */
    public function getPaReq(): ?string
    {
        return $this->paReq;
    }

    /**
     * Get the fields (names and values) to go into the paReq POST.
     * MD = Merchant Data; it is generated by the merchant site, i.e. it is
     * the merchant transaction ID (or an equivalent).
     * $termUrl is the return URL after the PA Request is complete. Add it here,
     * or set it explicitly in your form.
     *
     * @param string|null $termUrl The callback URL, if known at this point
     * @param string|null $md The Merchant Data, if known at this point
     * @return array List of parameter fields and values to go into the PA Req POST
     */
    public function getPaRequestFields(?string $termUrl = null, ?string $md = null): array
    {
        $fields = [
            'PaReq' => $this->getPaReq(),
        ];

        if (isset($termUrl)) {
            $fields['TermUrl'] = $termUrl;
        }

        if (isset($md)) {
            $fields['MD'] = $md;
        }

        return $fields;
    }

    /**
     * Convenient serialisation for logging and debugging.
     */
    public function jsonSerialize(): mixed
    {
        $return = parent::jsonSerialize();

        $return['transactionId'] = $this->transactionId;
        $return['acsUrl'] = $this->acsUrl;
        $return['paReq'] = $this->paReq;

        return $return;
    }

    /**
     * This is a 3D Secure redirect.
     */
    public function isRedirect(): bool
    {
        return true;
    }
}
